// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/calculate.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Calculation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculation) Reset() {
	*x = Calculation{}
	mi := &file_proto_calculate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculation) ProtoMessage() {}

func (x *Calculation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculation.ProtoReflect.Descriptor instead.
func (*Calculation) Descriptor() ([]byte, []int) {
	return file_proto_calculate_proto_rawDescGZIP(), []int{0}
}

func (x *Calculation) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type UserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Calculation   *Calculation           `protobuf:"bytes,3,opt,name=calculation,proto3" json:"calculation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	mi := &file_proto_calculate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculate_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDataRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDataRequest) GetCalculation() *Calculation {
	if x != nil {
		return x.Calculation
	}
	return nil
}

type UserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	mi := &file_proto_calculate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculate_proto_rawDescGZIP(), []int{2}
}

func (x *UserDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_calculate_proto protoreflect.FileDescriptor

const file_proto_calculate_proto_rawDesc = "" +
	"\n" +
	"\x15proto/calculate.proto\x12\x04user\"-\n" +
	"\vCalculation\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"z\n" +
	"\x0fUserDataRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x123\n" +
	"\vcalculation\x18\x03 \x01(\v2\x11.user.CalculationR\vcalculation\",\n" +
	"\x10UserDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2L\n" +
	"\vUserService\x12=\n" +
	"\fSendUserData\x12\x15.user.UserDataRequest\x1a\x16.user.UserDataResponseB\x0eZ\f./proto;userb\x06proto3"

var (
	file_proto_calculate_proto_rawDescOnce sync.Once
	file_proto_calculate_proto_rawDescData []byte
)

func file_proto_calculate_proto_rawDescGZIP() []byte {
	file_proto_calculate_proto_rawDescOnce.Do(func() {
		file_proto_calculate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculate_proto_rawDesc), len(file_proto_calculate_proto_rawDesc)))
	})
	return file_proto_calculate_proto_rawDescData
}

var file_proto_calculate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_calculate_proto_goTypes = []any{
	(*Calculation)(nil),      // 0: user.Calculation
	(*UserDataRequest)(nil),  // 1: user.UserDataRequest
	(*UserDataResponse)(nil), // 2: user.UserDataResponse
}
var file_proto_calculate_proto_depIdxs = []int32{
	0, // 0: user.UserDataRequest.calculation:type_name -> user.Calculation
	1, // 1: user.UserService.SendUserData:input_type -> user.UserDataRequest
	2, // 2: user.UserService.SendUserData:output_type -> user.UserDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calculate_proto_init() }
func file_proto_calculate_proto_init() {
	if File_proto_calculate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculate_proto_rawDesc), len(file_proto_calculate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculate_proto_goTypes,
		DependencyIndexes: file_proto_calculate_proto_depIdxs,
		MessageInfos:      file_proto_calculate_proto_msgTypes,
	}.Build()
	File_proto_calculate_proto = out.File
	file_proto_calculate_proto_goTypes = nil
	file_proto_calculate_proto_depIdxs = nil
}
